name: Comment on PR with conflict Label

on:
  pull_request:
    types: [labeled, unlabeled, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check for specific label
        if: contains(github.event.pull_request.labels.*.name, 'conflict')
        uses: actions/github-script@v7
        with:
          script: |
            const { context: aliasContext, github } = require('@actions/github');
            
            const commentBodyConflict = "@${aliasContext.actor} This PR has conflicts, please resolve them.";

            const existingComments = await github.rest.issues.listComments({
              owner: aliasContext.repo.owner,
              repo: aliasContext.repo.repo,
              issue_number: aliasContext.issue.number,
              per_page: 100, // GitHub API 限制，可能需要分页
            });


            let shouldComment = true;
            existingComments.data.forEach(comment => {
              if (comment.body.includes(commentBodyConflict)) {
                shouldComment = false;
              }
            });

            if (shouldComment) {
              await github.rest.issues.createComment({
                owner: aliasContext.repo.owner,
                repo: aliasContext.repo.repo,
                issue_number: aliasContext.issue.number,
                body: commentBodyConflict
              });
            }
