name: Comment on PR with conflict Label

on:
  pull_request:
    types: [labeled, unlabeled, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check for specific label
        if: contains(github.event.pull_request.labels.*.name, 'conflict')
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const existingComments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              per_page: 100, // GitHub API 限制，可能需要分页
            });

            const commentBody = "@${{ github.event.pull_request.user.login }} This PR has conflicts, please resolve them.";

            let shouldComment = true;
            existingComments.data.forEach(comment => {
              if (comment.body.includes(commentBody)) {
                shouldComment = false;
              }
            });

						if (shouldCommentLabel) {
							await github.rest.issues.createComment({
								owner: context.repo.owner,
								repo: context.repo.repo,
								issue_number: context.issue.number,
								body: commentBodyLabel,
							});
						}